version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: 
      - /bin/bash
      - -c
      - |
        /docker-entrypoint.sh cassandra -f &
        sleep 30
        cqlsh -e "CREATE KEYSPACE IF NOT EXISTS book_app WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1};"
        wait
  
  web:
    build: .
    container_name: express-cassandra-app-web
    ports:
      - "3000:3000"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - mynetwork
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

networks:
  mynetwork:
    driver: bridge
