version: '3.8'
services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: express-cassandra-app-web
    ports:
      - "3000:3000"
    depends_on:
      cassandra:
        condition: service_healthy

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
